import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import '@/styles/globals.scss'
import Navbar from "@/components/layout/navbar/Navbar";
import Header from "@/components/layout/navbar/Header";
import SessionProviderWrapper from "@/components/sessionProvider/SessionProviderWrapper";
import { i18n, Locale } from "../../../i18n.config";
import { LanguageProvider } from "@/context/LanguageContext";


const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Immersound",
  description: "Generated by create next app",
};

export async function generateStaticParams(){
  return i18n.locales.map(locale=>({lang:locale}))
}

export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode,
  params:{lang:Locale}  
}>) {
  return (

    <html lang="es">
        <body className={monserrat.className}>          
          <SessionProviderWrapper>
            <LanguageProvider initialLang={params}>
              <Header />
              {children}
            </LanguageProvider>
          </SessionProviderWrapper>
        </body>
      </html>
  );
}
