import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import '@/styles/globals.scss'
import Navbar from "@/components/layout/navbar/Navbar";
import Header from "@/components/layout/navbar/Header";
import SessionProviderWrapper from "@/components/sessionProvider/SessionProviderWrapper";


const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Immersound",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode;
  session:any
}>) {
  return (
    <html lang="en">
        <body className={monserrat.className}>
          <SessionProviderWrapper>
            <Header />
            {children}
          </SessionProviderWrapper>
        </body>
      </html>
  );
}
