import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import '@/styles/globals.scss'
import Navbar from "@/components/layout/navbar/Navbar";
import Header from "@/components/layout/navbar/Header";

const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Immersound",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <Header />
        {children}
        </body>
    </html>
  );
}
